# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

menu:
  主页: / || fas fa-home
  文章: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  友情链接: /link/ || fas fa-link

highlight_theme: mac


canvas_ribbon:
  enable: true
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false
  mobile: false

aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/chengeheng
  card_announcement:
    enable: true
    content: 欢迎来到我的个人博客
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works


subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: false
  # Effect Speed Options (打字效果速度參數)
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 150 # type speed in milliseconds
  backSpeed: 50 # backspacing speed in milliseconds
  # loop (循環打字)
  loop: true
  # source 調用第三方服務
  # source: false 關閉調用
  source: 3
  # source: 1  調用一言網的一句話（簡體） https://hitokoto.cn/
  # source: 2  調用一句網（簡體） http://yijuzhan.com/
  # source: 3  調用今日詩詞（簡體） https://www.jinrishici.com/
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  # source: false
  # 如果關閉打字效果，subtitle 只會顯示 sub 的第一行文字
  sub: 

# comments: 
#   use:  # Valine,Disqus,gitalk
#   text: true 
# giscus:
#   repo: chengeheng/chengeheng.github.io
#   repo_id: 16737760170
#   category_id: 38306178
#   theme:
#     light: light
#     dark: dark
#   option:
   
# https://valine.js.org
# valine:
#   enable: true
#   appId: dm7takfGZ4rwDbufDl5wWzxf-gzGzoHsz
#   appKey: abKef4Y3eZntv6K8qQkM0j1j
#   avatar: monsterid # gravatar style https://valine.js.org/#/avatar
#   serverURLs: https://chengeheng.github.io/ # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
#   lang: zh-cn
#   visitor: false


# gitalk:
#   enable: true
#   client_id: 3c203d6ed3e930db368a
#   client_secret: 7e88046d826b7326e745c0a6ba9056f58b36c727
#   repo: chengeheng.github.io
#   owner: chengeheng
#   admin: chengeheng
#   option:
#     language: zh-CN
#     perPage: 10
#     # distractionFreeMode: false
#     pagerDirection: last
#     createIssueManually: true
#     # count: false